name: Start eslint and deploy

on:
  push:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm i

      - name: Build
        working-directory: ./client
        run: npm run build

      - name: Run ESLint
        run: npm run lint
